# Created with YamlCreate.ps1 v2.0.7 using InputObject 🤖 $debug=QUSU-7-2-2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: jasongin.nvs
PackageVersion: 1.7.0
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nvs
ReleaseDate: 2022-12-08
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/jasongin/nvs/releases/download/v1.7.0/nvs-1.7.0.msi
  InstallerSha256: CA10C17653458A7301CB5BFFD0B84420DC22FE6AAE4A15728996AE13038CB836
  ProductCode: '{B4717CAE-A20E-409E-84BE-3A03EF684578}'
ManifestType: installer
ManifestVersion: 1.1.0
